//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareHouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoftwareHouseDBEntities1 : DbContext
    {
        public SoftwareHouseDBEntities1()
            : base("name=SoftwareHouseDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetProjectsByEId_Result> GetProjectsByEId(Nullable<int> eId)
        {
            var eIdParameter = eId.HasValue ?
                new ObjectParameter("EId", eId) :
                new ObjectParameter("EId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectsByEId_Result>("GetProjectsByEId", eIdParameter);
        }
    }
}
